module.exports = {

	/* Error Code : Error Description This error occures when no body is recieved from the request 
	*/
	'INFO-1' : 'No Data Recieved',
	/* This error is generated by Database when a Duplicate key error occurs */
	'11000' : 'Duplicate Key error',
	
}